import numpy as np
import pandas as pd

file = pd.read_csv("vgsales.csv")
num_ligne = file.shape[0]
num_column = file.shape[1]



incomplete_columun = []

print("Le fichier possède", num_ligne, "lignes et", file.shape[1], "colonnes")

for column in file:
    count_lines = file[column].isnull().sum()
    print("Sur les", num_ligne, "lignes, il y a", count_lines , "lignes avec des données manquantes dans la colonne", column)
    if count_lines > 0:
        incomplete_columun.append(column)

for column in incomplete_columun:
    res = file["Publisher"].dropna()
    print(res.isnull().sum())

# print(file["Publisher"].isnull().sum())

#Vérifier la valeur de retour


# This dataset contains a list of video games with sales greater than 100,000 copies. It was generated by a scrape of vgchartz.com.
#
# Fields include
#
#     Rank - Ranking of overall sales
#
#     Name - The games name
#
#     Platform - Platform of the games release (i.e. PC,PS4, etc.)
#
#     Year - Year of the game's release
#
#     Genre - Genre of the game
#
#     Publisher - Publisher of the game
#
#     NA_Sales - Sales in North America (in millions)
#
#     EU_Sales - Sales in Europe (in millions)
#
#     JP_Sales - Sales in Japan (in millions)
#
#     Other_Sales - Sales in the rest of the world (in millions)
#
#     Global_Sales - Total worldwide sales.
